export default {
  v: "5.7.8",
  fr: 30,
  ip: 0,
  op: 90,
  w: 500,
  h: 500,
  nm: "Giralda Animation",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Giralda",
      sr: 1,
      ks: {
        o: { a: 0, k: 100 },
        r: { a: 0, k: 0 },
        p: { a: 0, k: [250, 250, 0] },
        a: { a: 0, k: [0, 0, 0] },
        s: { a: 0, k: [100, 100, 100] },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [80, 300] },
              p: { a: 0, k: [0, 0] },
              r: { a: 0, k: 0 },
              nm: "Tower Base",
              mn: "ADBE Vector Shape - Rect",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.851, 0.384, 0.09, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [0, 50] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 0, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 30, s: [100, 100] },
                ],
              },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Tower",
        },
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [100, 30] },
              p: { a: 0, k: [0, 0] },
              r: { a: 0, k: 0 },
              nm: "Top Section",
              mn: "ADBE Vector Shape - Rect",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.804, 0.416, 0.18, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [0, -115] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 20, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 40, s: [100, 100] },
                ],
              },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Top Section",
        },
        {
          ty: "gr",
          it: [
            {
              ty: "sr",
              d: 1,
              pt: { a: 0, k: 5 },
              p: { a: 0, k: [0, 0] },
              ir: { a: 0, k: 15 },
              is: { a: 0, k: 0 },
              or: { a: 0, k: 30 },
              os: { a: 0, k: 0 },
              r: { a: 0, k: 0 },
              nm: "Star",
              mn: "ADBE Vector Shape - Star",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.851, 0.384, 0.09, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [0, -160] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 35, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 50, s: [100, 100] },
                ],
              },
              r: {
                a: 1,
                k: [
                  { t: 50, s: [0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 80, s: [360] },
                ],
              },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Giraldillo",
        },
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [120, 20] },
              p: { a: 0, k: [0, 0] },
              r: { a: 0, k: 0 },
              nm: "Base",
              mn: "ADBE Vector Shape - Rect",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.804, 0.416, 0.18, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [0, 200] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 0, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 20, s: [100, 100] },
                ],
              },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Base",
        },
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [15, 40] },
              p: { a: 0, k: [0, 0] },
              r: { a: 0, k: 0 },
              nm: "Window",
              mn: "ADBE Vector Shape - Rect",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.004, 0.004, 0, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [-25, 50] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 40, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 55, s: [100, 100] },
                ],
              },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Window 1",
        },
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [15, 40] },
              p: { a: 0, k: [0, 0] },
              r: { a: 0, k: 0 },
              nm: "Window",
              mn: "ADBE Vector Shape - Rect",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.004, 0.004, 0, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [0, 50] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 45, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 60, s: [100, 100] },
                ],
              },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Window 2",
        },
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [15, 40] },
              p: { a: 0, k: [0, 0] },
              r: { a: 0, k: 0 },
              nm: "Window",
              mn: "ADBE Vector Shape - Rect",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.004, 0.004, 0, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [25, 50] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 50, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 65, s: [100, 100] },
                ],
              },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Window 3",
        },
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [15, 40] },
              p: { a: 0, k: [0, 0] },
              r: { a: 0, k: 0 },
              nm: "Window",
              mn: "ADBE Vector Shape - Rect",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.004, 0.004, 0, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [-25, 0] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 55, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 70, s: [100, 100] },
                ],
              },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Window 4",
        },
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [15, 40] },
              p: { a: 0, k: [0, 0] },
              r: { a: 0, k: 0 },
              nm: "Window",
              mn: "ADBE Vector Shape - Rect",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.004, 0.004, 0, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [0, 0] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 60, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 75, s: [100, 100] },
                ],
              },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Window 5",
        },
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [15, 40] },
              p: { a: 0, k: [0, 0] },
              r: { a: 0, k: 0 },
              nm: "Window",
              mn: "ADBE Vector Shape - Rect",
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.004, 0.004, 0, 1] },
              o: { a: 0, k: 100 },
              r: 1,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
            },
            {
              ty: "tr",
              p: { a: 0, k: [25, 0] },
              a: { a: 0, k: [0, 0] },
              s: {
                a: 1,
                k: [
                  { t: 65, s: [0, 0], i: { x: [0.5], y: [1] }, o: { x: [0.5], y: [0] } },
                  { t: 80, s: [100, 100] },
                ],
              },
              r: { a: 0, k: 0 },
              o: { a: 0, k: 100 },
              sk: { a: 0, k: 0 },
              sa: { a: 0, k: 0 },
            },
          ],
          nm: "Window 6",
        },
      ],
      ip: 0,
      op: 90,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
}
