export const seoConfig = {
  siteName: "Sevify",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://sevify.es",
  defaultTitle: "Sevify | Diseño Web Moderno, Minimalista y Funcional",
  defaultDescription:
    "Sevify crea experiencias digitales con diseño web minimalista, interfaces intuitivas y alto rendimiento. Inspirado en la estética y la usabilidad.",
  defaultKeywords: [
    "diseño web moderno",
    "web minimalista",
    "diseño UI UX",
    "experiencia de usuario",
    "Sevify Studio",
    "interfaz digital",
    "frontend",
    "desarrollador web",
    "proyectos de diseño web",
    "diseño web Sevilla",
    "desarrollo web profesional",
    "agencia diseño web",
    "diseño responsive",
    "optimización web",
    "SEO web",
    "desarrollo frontend",
    "diseño web España",
    "agencia digital Sevilla",
    "creación páginas web",
    "diseño web corporativo",
  ],
  author: "Sevify",
  creator: "Sevify Team",
  publisher: "Sevify",
  language: "es-ES",
  region: "ES",
  city: "Sevilla",
  country: "España",
  businessType: "WebDesign",
  industry: "Technology",
  social: {
    twitter: "@sevify",
    instagram: "https://www.instagram.com/sevifyweb/",
    tiktok: "https://www.tiktok.com/@sevifyweb",
    linkedin: "https://www.linkedin.com/company/sevify/",
  },
}
